### ISSUE TITLE
Water coastline effect not z-stacked same on Tangram ES

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#101]
On the WebGL version of Tangram this water stroke is below the road (not above it). Location: San Francisco Golden Gate Bridge.

![screenshot_2015-11-30-22-05-18](https://cloud.githubusercontent.com/assets/853051/11493649/bd82d912-97af-11e5-9953-6a4b6130df99.png)

**Comment by matteblair** [comment]
Boy this was a weird one. Turns out that you've hit an Undefined Behavior!

The `order` for the highway feature is defined [here](https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L1127) as `8` and [here](https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L2146) as `function() { return (6 + feature.sort_key) || 6; }`. These rules both match the feature _at the same depth_ so there is no way to guarantee which will be applied, as explained [in the docs](https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/Filters-Overview.md#matching-collisions).

The `order` for the water boundary feature is defined [here](https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L966) as `10`. So depending on which `order` rule is used for the highway feature, the water boundary may appear above or below the highway (in fact, if you reload this scene in tangram-es several times you can see it switch order without any changes in the code or stylesheet! that's unordered mapping for you).

My recommendation for this specific issue would be to remove the first `order` definition of `8`. In general it is probably better for organization to not define order in multiple places, if possible.

**Comment by matteblair** [comment]
I also just noticed that this same behavior will occur with the path features on either side of the highway as well (their `order` is set to `6` [here](https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L1893)). 

This behavior almost certainly occurs in other instances as well, so I will re-iterate that setting `order` in multiple "parallel" rules is probably trouble.

**Comment by matteblair** [comment]
@bcamper as I mentioned, this oddity of "parallel" rules with undefined order can be hard to diagnose. 

Instead of leaving the behavior undefined, we could decide on an arbitrary (but consistent) order in which to apply rules with the same depth. For example, when conflicting rules are encountered we can take their values as strings, sort them by lexicographical order, then take the first value from the sorted collection.

**Comment by matteblair** [comment]
Behavior seems to match in both implementations now.
