### ISSUE TITLE
Remove duplicate YAML keys

### ISSUE THREAD

**Issue by bcamper** [tangrams/eraser-map#161]
There are currently two places with invalid YAML keys in the scene file:

https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L2107-L2109
(in this case, the `cap` is being inherited from the parent anyway, so maybe it could be removed, along with the `cap` setting under `outline`)

https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L4328-L4330
(this one is a pretty significant divergence in `priority`)

I would like to upgrade to a newer version of our YAML parser, but it turns out that duplicate keys are invalid, and the YAML parser now enforces this, meaning we can't upgrade until we fix these.

Unfortunately it seems that other styles (at least Refill and Cinnabar so far) also have duplicate keys (but different from these), so we'll need to do a sweep across them all.

**Comment by bcamper** [comment]
@nvkelso assigning partially to think about sweeping through other styles, not urgent, but making it difficult to complete https://github.com/tangrams/tangram/issues/254

**Comment by nvkelso** [comment]
Fixed in both Eraser Map and Skin & Bones repos.

The cap style thing definitely should have a refactor – brunnels and z-stacking remain weird but mostly fixed in Eraser Map. It's much more confused in Skin & Bones right now.

The neighbourhood priority was an easy fix (the large number was right & consistent with the previous use).
