### ISSUE TITLE
ANDROID: tilted buildings grid pattern is broken

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#51]
![screenshot_2015-10-08-13-51-34](https://cloud.githubusercontent.com/assets/466585/10379581/e92e4026-6dc3-11e5-86df-3936840dca51.png)

When I tilt the map, the grid shader doesn't draw on the extruded buildings
cc @bcamper @patriciogonzalezvivo @nvkelso

**Comment by bcamper** [comment]
Also cc @blair1618

**Comment by matteblair** [comment]
Ah yes, one of many known issues at the moment :)

The android build no longer has the very latest stylesheet, this behavior may be different after Brett's changes to building styles but it may still be broken in the very latest stylesheet because of how normal vectors are interpreted. 

The `normal` that is available in shader blocks is the surface normal _oriented relative to the camera_. This means that the value of `normal` for a single vertex can vary depending on how the camera is oriented. This isn't noticeable in tangram-js because the camera orientation is fixed. In general though, it is unreliable to test normals like [this](https://github.com/mapzen/eraser-map/blob/master/app/src/main/assets/eraser-map.yaml#L752) unless we establish a way to provide un-transformed normals for this purpose.

**Comment by bcamper** [comment]
@blair1618 so do we have it tracked to fix this?

**Comment by matteblair** [comment]
May be fixed with the changes you made to building styles, so I'm gonna
re-evaluate when we get those changes in the Android build

**Comment by bcamper** [comment]
I'm not optimistic, I don't believe I changed anything relating to normals
:)  Oh I was going to do that change to move the surface calculation to the
vertex shader, perhaps that's what you mean (that was not in the PR)... I'm
not sure that changes this though.
