### ISSUE TITLE
Water grid texture not visible on phone

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#69]
Don't see it on Galaxy S6 Edge

@blair1618 @tallytalwar 

![screenshot_2015-10-30-10-51-02-2](https://cloud.githubusercontent.com/assets/466585/10853715/bf51c5f6-7ef4-11e5-9d8f-793a0c032022.png)

**Comment by tallytalwar** [comment]
@sensescape can you try the latest build from android.mapzen.com? For me its working on S5.

**Comment by matteblair** [comment]
I've observed this on other phones as well (using the latest code and
styles). This is an unfortunate consequence of differences in GLSL
compilers among devices.

Most devices (and all webgl implementations) tolerate shaders that contain
incomplete function definitions so long as the function isn't called inside
the main method, but on some devices this will cause the shader to not
compile. We use one such function in the eraser-map shaders and because of
this, the water shader fails to compile on the S6 and a few other devices.

There are ways to work around this for eraser-map's shaders, but it's a
very annoying problem in general :\

**Comment by sensescape** [comment]
@tallytalwar Yes, I tried the latest. I'll try it again. Thanks! Yes @blair1618 , what's your recommendation? Shall we have 2 types of shaders then? Let me know how I can help.

**Comment by nvkelso** [comment]
@blair1618 and @tallytalwar Is this a regression, though? Both Geraldine and I remember this working before (but as those things go...).

**Comment by matteblair** [comment]
Yes, this is a regression (on certain devices).

I'll create a fix on the Android branch (using the gh-pages branch is
blocked for us by the 0.4 release of Tangram and the icon texture size).

**Comment by bcamper** [comment]
@blair1618 do you know what the offending GLSL is?

**Comment by matteblair** [comment]
https://github.com/tangrams/eraser-map/blob/android/eraser-map.yaml#L467

The dilemma is:

If `TileCoords` is defined in both the vertex and fragment shader, the dots style doesn't work correctly on some set of phones (the reason for this is a bit of a mystery). 

If `TileCoords` is not defined in both the vertex and fragment shader, the GLSL compilers on some phones won't compile the style (even though the function is only called in the shader where it's defined).

**Comment by tallytalwar** [comment]
120f6d1 should fix water grid on these selective devices (s6 s6-edge).
